[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-s",  # Strip symbols for smaller binary
]

# Environment variables can be set here as well
[env]
CC_x86_64_unknown_linux_musl = "x86_64-linux-musl-gcc"
CXX_x86_64_unknown_linux_musl = "x86_64-linux-musl-g++"
AR_x86_64_unknown_linux_musl = "x86_64-linux-musl-ar"
